//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string ArticleContent { get; set; }
        public string ArticleDate { get; set; }
        public string ArticleImage { get; set; }
        public string ArticleTags { get; set; }
        public string ArticleCategory { get; set; }
        public string ArticleMap { get; set; }
        public string ArticleType { get; set; }
    }
}
