//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingDetail
    {
        public int Id { get; set; }
        public Nullable<int> ListingId { get; set; }
        public string RoomType { get; set; }
        public string RoomName { get; set; }
        public Nullable<decimal> SizeW { get; set; }
        public Nullable<decimal> SizeL { get; set; }
        public string SizeUnits { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
