//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySiteEntities : DbContext
    {
        public MySiteEntities()
            : base("name=MySiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ImageGallery> ImageGalleries { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserListing> UserListings { get; set; }
        public virtual DbSet<Listing> Listings { get; set; }
        public virtual DbSet<ListingImageGallery> ListingImageGalleries { get; set; }
    }
}
