//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserListing
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Listing_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
